### ISSUE TITLE
problem lunching new servers 

### ISSUE THREAD

**Issue by WhittyWhitcomb12** [jsegaert/iocage-plugin-mineos#11]
hello im trying to launch a new server in mineos thats running in a jail on truenas 13 i hit run and it works for a few seconds then says that the server is down any help would be appreciated

**Comment by jsegaert** [comment]
Can you provide a few more details, so I can try to reproduce.

- The exact version of TrueNAS
- The profile of the MineOS server you're trying to install/start

**Comment by WhittyWhitcomb12** [comment]
truenas version 13.0-u4
prfile 1.19.4

**Comment by jsegaert** [comment]
Thank you.  Does the log for that server in the MineOs UI show anything useful?
First I would try to increase memory, set the -Xmx value to 4096 for 4 GiB

**Comment by WhittyWhitcomb12** [comment]
<html>
<body>


[11:03:11] [ServerMain/WARN]: File not found or not readable: /var/run/dmesg.boot
--
[11:03:11] [ServerMain/WARN]: File not found or not readable: /var/run/dmesg.boot
[11:03:18] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:03:19] [ServerMain/INFO]: Loaded 7 recipes
[11:03:20] [ServerMain/INFO]: Loaded 1179 advancements
[11:03:21] [Server thread/INFO]: Starting minecraft server version 1.19.4
[11:03:21] [Server thread/INFO]: Loading properties
[11:03:21] [Server thread/INFO]: Default game type: SURVIVAL
[11:03:21] [Server thread/INFO]: Generating keypair
[11:03:21] [Server thread/INFO]: Starting Minecraft server on *:25565
[11:03:21] [Server thread/INFO]: Using default channel type
[11:03:21] [Server thread/WARN]: **** FAILED TO BIND TO PORT!
[11:03:21] [Server thread/WARN]: The exception was: java.net.BindException: Address already in use
[11:03:21] [Server thread/WARN]: Perhaps a server is already running on that port?
[11:03:21] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Failed to initialize server
at net.minecraft.server.MinecraftServer.w(SourceFile:688) ~[server-1.19.4.jar:?]
at net.minecraft.server.MinecraftServer.a(SourceFile:266) ~[server-1.19.4.jar:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:03:21] [Server thread/WARN]: File not found or not readable: /var/run/dmesg.boot
[11:03:21] [Server thread/WARN]: File not found or not readable: /var/run/dmesg.boot
[11:03:21] [Server thread/ERROR]: This crash report has been saved to: /var/games/minecraft/servers/drunken_rage/./crash-reports/crash-2023-03-16_11.03.21-server.txt
[11:03:21] [Server thread/INFO]: Stopping server
[11:03:21] [Server thread/INFO]: Saving worlds
[11:03:21] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "aip.p_()" because "$5" is null
at net.minecraft.server.MinecraftServer.a(SourceFile:545) ~[server-1.19.4.jar:?]
at net.minecraft.server.MinecraftServer.t(SourceFile:606) ~[server-1.19.4.jar:?]
at ahq.t(SourceFile:536) ~[server-1.19.4.jar:?]
at net.minecraft.server.MinecraftServer.w(SourceFile:707) ~[server-1.19.4.jar:?]
at net.minecraft.server.MinecraftServer.a(SourceFile:266) ~[server-1.19.4.jar:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]


</body>
</html>




i had no other servers running when i tried to run it
and i have 8 GB of ram alocated to it

**Comment by WhittyWhitcomb12** [comment]
i have the ip set to 0.0.0.0 so the way i understand it 
it should find the next open port

**Comment by jsegaert** [comment]
Do you already have another minecraft server running on the default port 25565?
When you have more than one server active (running at the same time) in MineOS, they all need different ports.  Try incrementing the port to 25566 in the server settings. [You'll also need to change it in the Minecaft client so they match]

Or you could just stop the other servers.
